//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usr
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Age { get; set; }
        public string E_mail { get; set; }
        public string Imagepath { get; set; }
    }
}
